In [1]:
import numpy

In [2]:
# to check the version
numpy.__version__

'1.17.2'

In [3]:
# to import with an alias
import numpy as np

In [5]:
# to display the details of numpy
np?

Type:        module
String form: <module 'numpy' from '/home/pranav/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        ~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [15]:
# 
np.random.seed(0) # seed for reproducibilty

x1 = np.random.randint(10, size = 6) # 1-d array
x2 = np.random.randint(10, size = (3,4)) # 2-d array
x3 = np.random.randint(10, size = (3,4,5)) # 3-d array

In [16]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [ ]:
print(x3.ndim)
print(x3.shape)
print(x3.size)

In [ ]:
print(x3.dtype)

In [ ]:
print(x3.itemsize)
print(x3.nbytes)

In [ ]:
np.nbytes?

In [24]:
# indexing the numpy mulitdim array
x3[-1,-1,-1]

4

# Array Slicing
[start: stop: step]

In [26]:
# Array Slicing just like python
x3[::-1] # reversing

array([[[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]]])

# Numpy Subarrays
* These are views not copies of the array

In [27]:
# One D subarrays
x = np.arange(10) # https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html 


In [28]:
x[5::-2]

array([5, 3, 1])

In [31]:
print(x2)
print("*******")
print(x2[:2,:3])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
*******
[[3 5 2]
 [7 6 8]]


In [32]:
print(x2[:3,::2])

[[3 2]
 [7 8]
 [1 7]]


In [34]:
print(x2[:,0])
print("******")
print(x2[0,:])

[3 7 1]
******
[3 5 2 4]


In [38]:
print(x2[::-1,::-1])

[[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]


In [39]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [40]:
print(x2[:2,1:3])

[[5 2]
 [6 8]]


# Reshape
* Size of reshape arrays must match the size of array
* No-copy view
* can also use New-axis method of reshape

In [41]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
grid1 = np.array([1,2,3])
print(grid1)
grid1.reshape(1,3)

[1 2 3]


array([[1, 2, 3]])

In [45]:
print(len(grid1.reshape(1,3)))
print(len(grid1))

1
3


In [46]:
grid1[np.newaxis, :]

array([[1, 2, 3]])

In [47]:
grid1[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation
* joining the arrays
* Must have same dimensions for concatenation
* np.vstack
* np.hstack

In [51]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,4])
print(np.concatenate([arr1,arr2]))

[1 2 3 2 4 4]


In [56]:
grid2 = np.array([[1,2,4], [2,3,4]])
print(np.concatenate([grid2,grid2])) # by default along rows
grid4 = np.concatenate([grid2,grid2])
print(grid4.shape)

[[1 2 4]
 [2 3 4]
 [1 2 4]
 [2 3 4]]
(4, 3)


In [55]:
print(np.concatenate([grid2,grid2], axis=1)) # concat along columns
grid3 = np.concatenate([grid2,grid2], axis=1)
print(grid3.shape)

[[1 2 4 1 2 4]
 [2 3 4 2 3 4]]
(2, 6)


In [60]:
np.vstack([grid2,grid2])

array([[1, 2, 4],
       [2, 3, 4],
       [1, 2, 4],
       [2, 3, 4]])

In [59]:
np.hstack([grid2, grid2])

array([[1, 2, 4, 1, 2, 4],
       [2, 3, 4, 2, 3, 4]])

In [61]:
y = np.array([[99],[99]])
np.hstack([grid2, y])

array([[ 1,  2,  4, 99],
       [ 2,  3,  4, 99]])

# Array Splitting
* np.split
* np.hsplit
* np.vsplit

In [62]:
x = [1,2,3,45,45,2,3,4]
x1,x2,x3 = np.split(x, [3, 5]) # equivalent to [:3] ,[3,5], [5:]
print(x1, x2, x3)

[1 2 3] [45 45] [2 3 4]


In [63]:
grid = np.arange(12).reshape(3,4)

In [64]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
# upper, lower = np.vsplit(grid,[2]) # split horizontally row-wise
upper= np.vsplit(grid,[2]) # split horizontally row-wise
print(upper)
print("******")
print(lower)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
******
[[ 8  9 10 11]]


In [67]:
left , right = np.hsplit(grid,[2]) # split vertically column-wise
print(left)
print("****")
print(right)

[[0 1]
 [4 5]
 [8 9]]
****
[[ 2  3]
 [ 6  7]
 [10 11]]


# Aggregation
## Summing
* numpy.sum() faster, operation executed in compiled code
## Minimum
* numpy.min()
## Maximum
* numpy.max()

### Multidim array
* aggregate along a row or column
* Takes additional arg to specify the axis 


# What is an Axis
for shape of array (3,4,5)

axis = 0 is 3

axis = 1 is 4

axis = 2 is 5

## other fns

sum, prod, mean, std, var, argmin, argmax, etc.

In [ ]:
l = np.random.random(1000)
l

In [74]:
# python sum
print(sum(l))
%timeit sum(l)

504.8675078459403
187 µs ± 1.88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [73]:
print(np.sum(l))
%timeit np.sum(l)

504.8675078459403
5.27 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
big_array = np.random.rand(1000000)
print(sum(l))
%timeit sum(l)
print("************")
print(np.sum(l))
%timeit np.sum(l)

504.8675078459403
217 µs ± 30.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
************
504.86750784593966
5.21 µs ± 77.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
min(big_array), max(big_array)


(1.4057692298008462e-06, 0.9999994392723005)

In [78]:
np.min(big_array), np.max(big_array)

(1.4057692298008462e-06, 0.9999994392723005)

In [81]:
# Multi Dim Aggregation
M = np.random.random((3,4))
print(M)

[[0.74881851 0.61419643 0.43132339 0.37202734]
 [0.60431186 0.87810342 0.68073001 0.69608841]
 [0.10819367 0.17286397 0.56630746 0.57669189]]


In [82]:
M.sum()

6.4496563730255145

In [83]:
M.min(axis=0)

array([0.10819367, 0.17286397, 0.43132339, 0.37202734])

In [84]:
M.max(axis=1)

array([0.74881851, 0.87810342, 0.57669189])