# Universal Function
* quickly exec repeated operations
* Flexible

**Computations using vectorization is always efficient!**
* Two types 
### Unary 
### Binary

np.add, np.subtract, np.negative and so on 
[This link](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [1]:
import numpy as np

In [2]:
x = np.arange(6)
print("X        :", x);
print("X + 1       :", x+1);
print("X - 2      :", x-2);
print("X / 2       :", x/2);
print("X * 2       :", x*2);

X        : [0 1 2 3 4 5]
X + 1       : [1 2 3 4 5 6]
X - 2      : [-2 -1  0  1  2  3]
X / 2       : [0.  0.5 1.  1.5 2.  2.5]
X * 2       : [ 0  2  4  6  8 10]


In [3]:
print("-x   :", -x)
print("x ** 2  :", x ** 2)
print("x % 2  :", x % 2)

-x   : [ 0 -1 -2 -3 -4 -5]
x ** 2  : [ 0  1  4  9 16 25]
x % 2  : [0 1 0 1 0 1]


In [4]:
-(0.3*x - 1) ** 2

array([-1.  , -0.49, -0.16, -0.01, -0.04, -0.25])

In [5]:
np.add(x, 2)

array([2, 3, 4, 5, 6, 7])

In [8]:
x = np.array([2,1,-2,-4])
np.absolute(x) # np.abs also wokrs

array([2, 1, 2, 4])

In [12]:
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
# inverse trig
x = [-1,0,1]
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[ 0. nan nan]
[1.57079633        nan        nan]
[0.         1.00388482 1.26262726]


/home/pranav/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in arcsin
  This is separate from the ipykernel package so we can avoid doing imports until
/home/pranav/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in arccos
  after removing the cwd from sys.path.


In [16]:
# Exponents
x = [1,2,4]
print(np.exp(x)) # to base e
print(np.exp2(x)) # base 2
print(np.power(3, x)) # base 3 

[ 2.71828183  7.3890561  54.59815003]
[ 2.  4. 16.]
[ 3  9 81]


In [18]:
# logarithms natural, to base-2 and to base-10
x= [1,2,3,4,10]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229 1.38629436 2.30258509]
[0.         1.         1.5849625  2.         3.32192809]
[0.         0.30103    0.47712125 0.60205999 1.        ]


# Scipy.special 
[Link](https://docs.scipy.org/doc/scipy/reference/special.html)

In [19]:
from scipy import special

In [22]:
# Gamma Func

x = [1, 3, 4]
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x,2))

[1. 2. 6.]
[0.         0.69314718 1.79175947]
[0.5        0.08333333 0.05      ]


# Advanced Ufunc Features

In [23]:
x = np.arange(5)
y = np.empty(5)
print(y)
np.multiply(x, 10, out = y)
print(y)

[0.         0.30103    0.47712125 0.60205999 1.        ]
[ 0. 10. 20. 30. 40.]


In [24]:
y = np.zeros(10)
print(y)
np.power(2,x, out=y[::2])
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [26]:
x = np.arange(1,6)
print(x)
print(np.add.reduce(x)) # look this up maybe like parent of np.sum() calling reduce results in sum on all arr elements
print(np.sum(x))

[1 2 3 4 5]
15
15


In [27]:
# accumulate fpr intermidiate results
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [29]:
# Outer products, to create multiplication table
x = np.arange(1,10)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

# Broadcasting

## 3 Rules

1. 

In [36]:
print(np.arange(3)+5)
print(np.ones((3,3)) + np.arange(3))
print(np.arange(3).reshape(3,1) +np.arange(3))
print(np.ones((3,2))+np.arange(3)) # Violates? rule 3 

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 