# Function
* quickly exec repeated operations
* Flexible

**Computations using vectorization is always efficient!**
* Two types 
### Unary 
### Binary

np.add, np.subtract, np.negative and so on 
[This link](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [1]:
import numpy as np

In [2]:
x = np.arange(6)
print("X        :", x);
print("X + 1       :", x+1);
print("X - 2      :", x-2);
print("X / 2       :", x/2);
print("X * 2       :", x*2);

X        : [0 1 2 3 4 5]
X + 1       : [1 2 3 4 5 6]
X - 2      : [-2 -1  0  1  2  3]
X / 2       : [0.  0.5 1.  1.5 2.  2.5]
X * 2       : [ 0  2  4  6  8 10]


In [3]:
print("-x   :", -x)
print("x ** 2  :", x ** 2)
print("x % 2  :", x % 2)

-x   : [ 0 -1 -2 -3 -4 -5]
x ** 2  : [ 0  1  4  9 16 25]
x % 2  : [0 1 0 1 0 1]


In [4]:
-(0.3*x - 1) ** 2

array([-1.  , -0.49, -0.16, -0.01, -0.04, -0.25])

In [5]:
np.add(x, 2)

array([2, 3, 4, 5, 6, 7])

In [8]:
x = np.array([2,1,-2,-4])
np.absolute(x) # np.abs also wokrs

array([2, 1, 2, 4])

In [12]:
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
# inverse trig
x = [-1,0,1]
print(np.arcsin(theta))
print(np.arccos(theta))
print(np.arctan(theta))

[ 0. nan nan]
[1.57079633        nan        nan]
[0.         1.00388482 1.26262726]


/home/pranav/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in arcsin
  This is separate from the ipykernel package so we can avoid doing imports until
/home/pranav/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in arccos
  after removing the cwd from sys.path.


In [16]:
# Exponents
x = [1,2,4]
print(np.exp(x)) # to base e
print(np.exp2(x)) # base 2
print(np.power(3, x)) # base 3 

[ 2.71828183  7.3890561  54.59815003]
[ 2.  4. 16.]
[ 3  9 81]


In [18]:
# logarithms natural, to base-2 and to base-10
x= [1,2,3,4,10]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229 1.38629436 2.30258509]
[0.         1.         1.5849625  2.         3.32192809]
[0.         0.30103    0.47712125 0.60205999 1.        ]
